# Use an appropriate base image with Java (e.g., OpenJDK)
FROM maven:3.9.6-eclipse-temurin-21 AS builder

# Set the working directory inside the container
WORKDIR /app

# Copy the entire uce.portal directory
COPY ./uce.portal ./uce.portal

# Override the default config

COPY ./kubernetes-corpus-importer/17-10-uceConfig.json /app/config/uceConfig.json
COPY ./uce.portal/uce.common/src/main/resources/common-kube.conf /app/uce.portal/uce.common/src/main/resources/common.conf
ADD ./team-images/ /app/uce.portal/uce.web/src/main/resources/public/img/


#COPY ./uce.portal/uce.common/src/main/resources/common.conf /app/uce.portal/uce.common/src/main/resources/common.conf

# Set the working directory to uce.portal
WORKDIR /app/uce.portal


# We are also building the target jar here; we only need uce.web
RUN mvn clean install -DskipTests -pl uce.web -am

FROM openjdk:22-jdk-slim
COPY ./kubernetes-corpus-importer/17-10-uceConfig.json /app/config/uceConfig.json
# Expose the port that your Spark application runs on
EXPOSE 4567

COPY --from=builder /app/uce.portal/uce.web/target/webportal-jar-with-dependencies.jar /app/uce.portal/uce.web/target/webportal-jar-with-dependencies.jar

# Copy the resources that aren't bundled in the jar
COPY ./uce.portal/resources /app/uce.portal/resources

WORKDIR /app/uce.portal/uce.web/
COPY ./database ../../database
# Command to run the application
# The name webportal.jar is finalized in the pom.xml of the uce.web project.
# Maybe: "-jar-with-dependencies" needs to be added behind webportal

#CMD ["java", "-jar", "./target/webportal-jar-with-dependencies.jar"]
