uce.version = 0.0.5

# University scraping and bib properties
university.botanik.base.url=https://sammlungen.ub.uni-frankfurt.de/botanik/periodical/titleinfo/{ID}
university.collection.base.url=https://sammlungen.ub.uni-frankfurt.de

# Gbif scraping properties
gbif.occurrences.search.url=https://api.gbif.org/v1/occurrence/search?limit=10&media_type=stillImage&taxon_key={TAXON_ID}

# RAG Webserver properties
rag.webserver.base.url=http://uce-rag-service:5678/

# JenaSparksql properties
sparql.host=http://uce-kube-sparql:5430/
#sparql.host=http://localhost:16543/
sparql.endpoint=biofid-search/sparql

templates.location=../resources/templates/
external.public.use=false
external.public.location=target/classes/public
database.scripts.location=../../database/

# We want to use an external path for developing to enable hot reloading
external.public.use=true


log.db=true
# Define the interval in seconds
session.job.interval = 3600
system.job.interval = 10

postgresql.connection.driver_class=org.postgresql.Driver
postgresql.dialect=org.hibernate.dialect.PostgreSQL162Dialect
postgresql.hibernate.connection.url=jdbc:postgresql://uce-postgresql-db:5432/uce
#postgresql.hibernate.connection.url=jdbc:postgresql://172.17.0.2:8010/uce 
#db connection is wrong
postgresql.hibernate.connection.username=postgres
postgresql.hibernate.connection.password=1234

postgresql.hibernate.current_session_context_class=thread
postgresql.hibernate.show_sql=false
postgresql.hibernate.format_sql=true
postgresql.hibernate.hbm2ddl.auto=update


#postgresql.hibernate.connection.url=jdbc:postgresql://141.2.140.66:5432/uce_test
#postgresql.hibernate.connection.username=uce_test_user
#postgresql.hibernate.connection.password=rRqAgi1RRdw59s6lyg8F


# s3 storage
minio.endpoint = http://localhost:9000
minio.username = admin
minio.pwd = 12345678
minio.bucket = cas

# Keycloak authentication
keycloak.realm=uce
keycloak.auth_server_url=http://localhost:8080
keycloak.client=uce-web
keycloak.credentials.secret=**********
